name: build-and-publish

on: [push]

jobs:
  build:
    name: Build binaries and release preview build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    permissions:
      contents: write

    steps:

    - name: Check out Repository
      uses: actions/checkout@v4

    - name: Build Flatpak
      run: |
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak remote-add --user --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
        flatpak --user remote-modify --enable flathub
        flatpak --user remote-modify --enable flathub-beta
        flatpak --user install -y flathub-beta org.freedesktop.Sdk.Extension.node22//24.08
        git config --global --add safe.directory /__w/qobuz-linux/qobuz-linux
        flatpak-builder --user --disable-rofiles-fuse --install-deps-from=flathub --force-clean _build flatpak/dev.mukkematti.qobuz-linux.yml --extra-sources=generated-sources.json
        flatpak build-bundle _repo qobuz-linux-${{ env.VERSION }}.flatpak dev.mukkematti.qobuz-linux

    - name: Release Artifacts
      uses: "softprops/action-gh-release@v2"
      with:
        tag_name: "${{ env.VERSION }}"
        prerelease: true
        name: "Development Build based on commit ${{ env.COMMIT }}"
        files: |
          qobuz-linux-aarch64-${{ env.VERSION }}.flatpak
          qobuz-linux-x86_64-${{ env.VERSION }}.flatpak

    
