name: build-and-publish

on: [push]

jobs:
  build:
    name: Build binaries and release preview build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    permissions:
      contents: write

    steps:

    - name: Check out Repository
      uses: actions/checkout@v4

    - name: Install Xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Set git safe.directory
      run: git config --global --add safe.directory /__w/qobuz-linux/qobuz-linux

    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        manifest-path: flatpak/dev.mukkematti.qobuz-linux.yml
        bundle: qobuz-linux-${{ env.VERSION }}.flatpak
        cache-key: flatpak-builder-${{ github.sha }}
        disable-rofiles-fuse: true

    - name: Release Artifacts
      uses: "softprops/action-gh-release@v2"
      with:
        tag_name: "${{ env.VERSION }}"
        prerelease: true
        name: "Development Build based on commit ${{ env.COMMIT }}"
        files: |
          qobuz-linux-${{ env.VERSION }}.flatpak

    
