name: build-and-publish

on: [push]

jobs:
  build:
    name: Build binaries and release preview build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Check out Repository
      uses: actions/checkout@v4

    - name: Prep Version String in package.json
      run: |
        version="$(cat VERSION)-$(git log --pretty=format:'%h' -1)"
        echo "COMMIT=$(git log --pretty=format:'%h' -1)" >> $GITHUB_ENV
        echo "VERSION=$version" >> $GITHUB_ENV
        jq --arg version "$version" '.version = $version' package.json > temp.json
        mv temp.json package.json

    - name: Install Xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        manifest-path: flatpak/dev.mukkematti.qobuz-linux.yml
        bundle: qobuz-linux-${{ env.VERSION }}.flatpak
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Release Artifacts
      uses: "softprops/action-gh-release@v2"
      with:
        tag_name: "${{ env.VERSION }}"
        prerelease: true
        name: "Development Build based on commit ${{ env.COMMIT }}"
        files: |
          qobuz-linux-${{ env.VERSION }}.flatpak

    
